### PR TITLE
Issue-24: Landing Page Created

### PR DESCRIPTION
**Pull request by mahamshahid18**
#### Tracking Issue: #24 

* Added `landing.html` as the base html file for landing page (as index.html was not available)
* Created a `styles` folder for all the scss and css files
* Added vendor libraries
* Added gulpfile for compiling styles from SASS to CSS

### CODE REVIEW

**Comment by poush** [comment]
Hi @mahamshahid18, thanks for the PR. Please do move the code into `gh-pages` branch with no project source in it except these website files. Also, I would like to suggest you to look on completely static pages as well. Building Gulp will add another travis task. If you are not familiar with `Jekyll`, it is automatically compiled in Github pages. I liked those three feature cards, so in any case I would like to see them in the final changes. If I may, I would like to suggest one template, which is pretty basic but is static based on Jekyll http://pietro.menna.net.br/jekyll-architect-theme/

Feel free to ask me any questions here. Please do also look into Jekyll as I think it will also be helpful there to write change logs as a blog.

**Comment by mahamshahid18** [comment]
Ok @poush I'll make the changes as requested. And yes, I know about Jekyll although I've never used it before. I'll take a look to see how my work can be incorporated into a Jekyll theme 👍

**Comment by mahamshahid18** [comment]
Ok so I did some searching. As I'm using Windows, installing and getting Jekyll set up is a real hassle (since it's based on Ruby), which I want to avoid at the moment.
Instead, I can move the files to the `gh-pages` branch for now. And then you can create another issue for moving it into Jekyll. Does that sound ok?

**Comment by poush** [comment]
Sure, please move them to `gh-pages`. We can definitely continue on further improvements at separate issues.

**Comment by mahamshahid18** [comment]
Perfect. Which branch do you want me to make a PR for? (I noticed that the project doesn't have a `gh-pages` branch). I have the branch in my project. But where do I merge it?

**Comment by poush** [comment]
Yes forgot to add gh-pages branch here. Added now, please change the branch to gh-pages and also prepare any necessary changes into `.gitignore`

**Comment by mahamshahid18** [comment]
Hmm I'm not sure why but the PR was automatically closed 🤔
I'll create a new PR, we can just leave this one @poush

**Pull request closed without merging**
