### PR TITLE
Updated icon from He to H2

### PR DESCRIPTION
**Pull request by stefangutnickallen**
#### Tracking Issue: #20 

- Changed He to H2, more in line with application 
- Optimized icon code 
- Beautified icon code

### CODE REVIEW

**Comment by poush** [comment]
Can you rebase your branch?

**Comment by stefangutnickallen** [comment]
Will do asap

**Comment by stefangutnickallen** [comment]
Hey @poush , I'm new to git. I deleted my fork and made a new PR.
 I guess you can close this one? Cheers

**Comment by poush** [comment]
No worries. Closing this.

**Pull request closed without merging**
